# -*- coding: utf-8 -*-
{
    'name': 'pr_custom_purchase',
    'summary': 'Custom purchase requisition backend workflow',
    'description': 'Backend-only custom purchase requisition and approval workflow.',
    'author': 'My Company',
    'website': 'https://www.yourcompany.com',
    'category': 'Operations',
    'version': '17.0.1.0.0',
    'license': 'LGPL-3',
    'depends': ['base', 'product', 'hr', 'mail', 'web', 'purchase', 'purchase_stock', 'stock', 'bus', 'project', 'account'],
    'data': [
        'security/custom_pr_groups.xml',
        'security/record_rules.xml',
        'security/ir.ui.menu.xml',
        'security/purchase_requisition_security.xml',
        'security/quotation_security.xml',
        'security/ir.model.access.csv',
        'views/custom_pr_views.xml',
        'views/inventory.xml',
        'views/remarks_popup.xml',
        'views/grn_report.xml',
        'views/remove_purchase_reports.xml',
        'views/custom_pr_templates.xml',
        'views/views.xml',
        'views/quotation.xml',
        'views/cash_odoo_ui.xml',
        'views/pr_odoo_ui.xml',
        'views/project_view.xml',
        'views/purchase_order_inherit.xml',
        'views/res_users_supervisor.xml',
        'data/custom_pr_ir_sequence_data.xml',
        'data/mail_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'pr_custom_purchase/static/src/css/style.scss',
            'pr_custom_purchase/static/src/js/script.js',
            'pr_custom_purchase/static/src/xml/form.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
